### ISSUE TITLE
v1.2 Boards from PCB.IO

### ISSUE THREAD

**Issue by anthonyjclarke** [hallard/WeMos-Matrix-Shield#1]
Hi, great work BTW!

I recently ordered some, arrived but they are the v1.0 :( ... if I order again will they definitely be 1.2? ;-) If I look at the link - https://pcbs.io/share/zMPKb seems to show v1.0 boards?

**Comment by hallard** [comment]
Thanks for pointing that, I'm sorry the link was the old one, they are 2 versions on PCBs.io, here is the correct link
https://PCBs.io/share/rG9w7
BTW, I fixed the repo also
