### ISSUE TITLE
Wiring / Assembling issues

### ISSUE THREAD

**Issue by anthonyjclarke** [hallard/WeMos-Matrix-Shield#2]
Ordered some 1.2 boards and not having any success wiring up, spent a few hours on this.

Wondering if you have used / have any photos to share?

Seems, I think, my issue is the J1 connector.  The pins on the PCB :- 

![greenshot 2018-10-01 17 11 52](https://user-images.githubusercontent.com/9491428/46274610-616ef880-c59d-11e8-9bef-019d735fb656.png)

Dont seem to align with Hari's image from his instructable site,

![fknu38wjj4zwi7l large](https://user-images.githubusercontent.com/9491428/46274637-73509b80-c59d-11e8-9bb1-dd3a86d734e0.jpg)

Is there an issue here as I cannot see R0?

**Comment by hallard** [comment]
I do not have received yet the 1.2 boards, so I can't test at all
The J1 connector should go straight to the output of the Matrix Board with a 6 pin ISP Connector 
 
![image](https://user-images.githubusercontent.com/2471931/46275179-4f209a80-c55c-11e8-9dbd-32d32931b460.png)

And yes the trick is that it's not aligned (was my error on PCB 1.0)
As you can see, J1 is matrix in pinout going to matrix out
in the example:

 - J1 pin 1 (so R1 for matrix in) goes to matrix out pin R0 according the following table
 - J1 pin 6 (so B0 for matrix in) goes to matrix out pin G1 according the following table

![image](https://user-images.githubusercontent.com/2471931/46275259-9e66cb00-c55c-11e8-891c-135e0c716527.png)

I must admit it gave me some headaches ;-)

**Comment by anthonyjclarke** [comment]
Thanks. I will try again tomorrow. 

Do you have any photos showing a built PCB and all wired up?

**Comment by anthonyjclarke** [comment]
I had to buy 10 PCB's, dont need them all, to thank you for your effort I'm happy to post you some if you want to DM your postal address? Can send today...

**Comment by anthonyjclarke** [comment]
I had to buy 10 PCB's, dont need them all, to thank you for your effort I'm happy to post you some if you want to DM your postal address? Can send today...

**Comment by dragondaud** [comment]
I received some 1.2 boards a couple days ago, and am having trouble. I checked all the boards, and there is no continuity between G1 input and output. I looked at the board file, and it is missing a trace. There is an "air wire" between input side G1 and the Output side. that should connect to G0. I'll try putting in a wire and see if that cures my lower-half display issues...

**Comment by dragondaud** [comment]
Verified: adding wire from G1 input to the pin labeled G1 (which goes to G0) on output fixes board, and it now works great. Images posted at https://plus.google.com/+DavidDenney/posts/U9e3iqzTEP9

**Comment by hallard** [comment]
@dragondaud, @anthonyjclarke 
thanks for reporting, I fixed this error. Amazing checked on V1.1 boards, and trace was there, a bad cut on eagle when creating V1.2 and voilà. Here is the visual fix

![fix-v12-wire](https://user-images.githubusercontent.com/2471931/46570227-44ea0c00-c961-11e8-80c7-cda6b8e20f40.jpg)

Anyway it's now fixed in V1.3, links and documentation has been updated and also PCBs.io boards.

@dragondaud  just saw your firmware, all I wanted to do, so thanks a lot, I'll try it ASAP

Thanks to @anthonyjclarke for the PCB, but I already have a lot here, so I don't need them  ;-)

**Comment by anthonyjclarke** [comment]
Thanks @hallard I'll make the modification.  I've now got some ISP Connector cables, so all ready to try again!

Would be a help for me, visually, if you could show some photos of the assembled PCB's (orientation of connectors etc).  Do you have any you can post?

**Comment by anthonyjclarke** [comment]
> I received some 1.2 boards a couple days ago, and am having trouble. I checked all the boards, and there is no continuity between G1 input and output. I looked at the board file, and it is missing a trace. There is an "air wire" between input side G1 and the Output side. that should connect to G0. I'll try putting in a wire and see if that cures my lower-half display issues...

@dragondaud do you have any "assembled" photos of a working configuration you could share please?  I've checked your G+ page, some of the PCB and sockets/orientation etc? ;-)

**Comment by hallard** [comment]
Guys, 

I've updated the [Readme.md](https://github.com/hallard/WeMos-Matrix-Shield/blob/master/README.md#assembled-boards) and put some pictures, take a look on it.

Also updated board to V1.4

Sorry for now pictures are from my old V1.0 board
