### ISSUE TITLE
v1.4 "Enhancement" Request!

### ISSUE THREAD

**Issue by anthonyjclarke** [hallard/WeMos-Matrix-Shield#3]
Hi, assembled and seem to have working with @dragondaud guidance as well... with assistance from his photo's https://plus.google.com/+DavidDenney/posts/U9e3iqzTEP9 would like to get the Power socket moved so it can sit "Flush".

![greenshot 2018-10-21 17 45 19](https://user-images.githubusercontent.com/9491428/47264017-2be47c00-d559-11e8-98a2-c861bb7721c8.png)

![greenshot 2018-10-21 17 47 34](https://user-images.githubusercontent.com/9491428/47264029-8251ba80-d559-11e8-8021-c892e1fe53d8.png)

Would also be fantastic if there was some way to have the PCB support @dragondaud temp monitoring without having to cut the trace... 

https://github.com/dragondaud/myClock
 
![greenshot 2018-10-21 17 44 54](https://user-images.githubusercontent.com/9491428/47264033-9e555c00-d559-11e8-946e-eaae5423fdaf.png)

Happy to place a "tip in the jar" :)

**Comment by hallard** [comment]
@anthonyjclarke 
I'm sorry I was not aware of this issue, in fact boards have been made to be plugged directly on the matrix boards, avoiding wiring and plugging connector on the bottom of the board

I've updated the [Readme.md](https://github.com/hallard/WeMos-Matrix-Shield/blob/master/README.md#assembled-boards) and put some pictures, take a look on it.

On next revision I will add also a 3 pins to connect DS18B20 connector directly and trying to move the barrel jack connector to avoid your issue.

**Comment by hallard** [comment]
Updated Repo and PCBs.io to V1.4

**Comment by dragondaud** [comment]
Ah, when I first received my v1.2 boards there wasn't much information on assembly, so I just winged it.... Attaching directly seems like a great idea. I will update the BOM in myClock for that configuration. :)
