### ISSUE TITLE
Power Header for PCB

### ISSUE THREAD

**Issue by anthonyjclarke** [hallard/WeMos-Matrix-Shield#4]
Hi

Thanks for all your Dev here, brilliant.. you should have a "Tip Jar" :)

Will order some 1.4 boards, before I do... I noticed that the Power Headers I bought from Aliexpress - http://tinyurl.com/y7eymwsj do not seem to fit the PCB.  They align with the Power Cable from the displays I have.

![greenshot 2018-10-22 06 18 10](https://user-images.githubusercontent.com/9491428/47271236-882fb600-d5c2-11e8-8048-b6aec95a1661.png)

![image](https://user-images.githubusercontent.com/9491428/47271214-53bbfa00-d5c2-11e8-9aa6-f87ec1c2b9f4.png)

Is this my error in ordering? or the wrong connector on the PCB?

Thanks

**Comment by hallard** [comment]
Correct, this connector is 3.96mm was not aware about this one, I knew 3.50mm or 5.08mm one, I'll change the PCB ASAP
Would you have one to send me by postal service ?

**Comment by anthonyjclarke** [comment]
No need to send, I will order when you have updated the PCB :)

Really appreciate your help here!

Built another version today... using a more compact LED display - P2.5 64x32 http://tinyurl.com/ycgdvj3t , so may have to think about the display connector again...

![greenshot 2018-10-22 21 33 51](https://user-images.githubusercontent.com/9491428/47288613-8c9bb380-d642-11e8-978c-8c7fa3d9af69.png)

Bit too close to the power connector...

![greenshot 2018-10-22 21 33 38](https://user-images.githubusercontent.com/9491428/47288650-bce35200-d642-11e8-9512-1455ade18abd.png)
![greenshot 2018-10-22 21 34 15](https://user-images.githubusercontent.com/9491428/47288651-bead1580-d642-11e8-9f5e-88d803555f89.png)
![greenshot 2018-10-22 21 34 03](https://user-images.githubusercontent.com/9491428/47288657-c10f6f80-d642-11e8-9551-4e5f695832ee.png)

:)

**Comment by hallard** [comment]
Damned, it will start to be complicated 
best would be to be able to plug also on the power connector ;-)

**Comment by anthonyjclarke** [comment]
No need to send, I will order when you have updated the PCB :)

Really appreciate your help here!

**Comment by anthonyjclarke** [comment]
@hallard Could I please ask a big favour :) 
Going to order from jlcpcb.com some 1.4 boards (quicker than pcb.io)
They have just told me the gerbers I created from Eagle are not valid, is there any way you could export gerber files and share (please) ? :)

**Comment by hallard** [comment]
@anthonyjclarke 
I'm using Eagle also, that' strange, default settings doesn't work. Which CAM job did you used to generate gerber files?
Does jlcpcb provide any cam job to generate gerbers?
Anyway I've put gerber file on the repo (used SeeedStudio CAM file as always) and that's for Matrix Shield Board Version 1.5 that should fix you issues ;-)
Pcbs.io and github repo have been updated to reflect new changes
Let me know if gerbers are ok.

**Comment by anthonyjclarke** [comment]
@hallard Thanks for this... Looks perfect, like the new version... *IF* there ever is a 1.6 then I've had some issues in Temp Sensors being so close to the Wemos / perhaps move that to the outside of the board.... I may mount on wire in any case.  Thanks again!

**Comment by dragondaud** [comment]
I'v been using [waterproof DS18B20](http://a.co/d/5qSImdf) which come on a long wire, but I put clocks inside shadow box frames, and I wanted the temp sensor outside of that, even.

**Comment by hallard** [comment]
Yes, I had some problem with NodeMCU board when I but SI7021 on board shield sensor, temp sensor need to be far from CPU board, because value is higher than real.
May be adding an "offset" option could help, but the best is the DS18B20 waterproof, just a hole in the case to get sensor out.
